apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-vault-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-vault
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3000"
      labels:
        app: secure-vault
    spec:
      containers:
      - name: secure-vault
        image: secure-vault:jenkins-latest
        imagePullPolicy: Never # Crucial for Minikube local images
        envFrom:
        - secretRef:
            name: vault-secrets